Prototype aerial segmentation application
Sydney-Informatics-Hub/aerial-segmentation pull request #20
Opened 2023-09-08 07:17 UTC by hlydecker

Showcase minimal functionality with a gradio application

2023-09-08 07:18 UTC, hlydecker commented
Work in progress

2023-09-11 06:57 UTC, hlydecker commented
Broken huggingface space work in progress: https://huggingface.co/spaces/SIH/building-segmentation/blob/main/app.py

2023-09-28 05:18 UTC, hlydecker commented
Weird behaviour on HF spaces 
![image](https://github.com/Sydney-Informatics-Hub/aerial-segmentation/assets/50643975/d6c365cb-a429-48ea-a585-21eb2316e4b0)

2023-09-28 06:53 UTC, hlydecker commented
Problem solved: weights must be paired with their config's yaml.

Model on here: https://unisyd.sharepoint.com/:f:/t/SydneyInformaticsHub2/EhqN2ERFn_pJsw1JQRchJZMBV6WP_UoWyh_IzHgIt5M9PQ?e=b6axTV

TODO: Add map for visualising inputs and outputs:

https://towardsdatascience.com/building-a-smart-travel-itinerary-suggester-with-langchain-google-maps-api-and-gradio-part-3-90dc7be627fb

2023-10-03 23:54 UTC, sahandv requested changes
Aside from some cosmetic issues, there are only a few comments to fix and make the merging easier.
Also if possible, and if not done already, let's `poc_gradio.py` through a pre-commit.

2023-10-03 23:54 UTC, sahandv commented on notebooks/prediction_scratch.ipynb
Skipped this one, as I assume it will change a lot. But we can add just an intro for now.

2023-10-03 23:54 UTC, sahandv commented on aerial-seg/poc_gradio.py
> +"""
Out of curiosity, what is the string for? Is this just a commented-out section? Or it does do something in gradio?
```
"""
gr_slider_confidence = gr.inputs.Slider(0,1,.1,.7,
                                        label='Set confidence threshold % for masks')
"""
```

2023-10-03 23:54 UTC, sahandv commented on aerial-seg/poc_gradio.py
> +description = "An instance segmentation demo for identifying boundaries of buildings in aerial images using DETR (End-to-End Object Detection) model with MaskRCNN-101 backbone"
We can just add a dot to the end to fix the punctuation in the description.

2023-10-04 08:10 UTC, hlydecker commented on aerial-seg/poc_gradio.py
> +"""
This is a rough draft of a slider UI element allowing users to specify the model's prediction threshold.

2023-10-04 08:11 UTC, hlydecker commented on aerial-seg/poc_gradio.py
> +description = "An instance segmentation demo for identifying boundaries of buildings in aerial images using DETR (End-to-End Object Detection) model with MaskRCNN-101 backbone"
```suggestion
description = "An instance segmentation demo for identifying boundaries of buildings in aerial images using DETR (End-to-End Object Detection) model with MaskRCNN-101 backbone."
```

2023-10-12 00:13 UTC, hlydecker commented on aerial-seg/poc_gradio.py
> +
Added documentation! Can I get approval to merge? :D

2023-10-12 00:18 UTC, xinwei89 commented on scripts/poc_gradio.py
> +cfg.MODEL.ROI_HEADS.NUM_CLASSES = 8
Dumb question, but can I ask how do we know there is 8 classes in this model? Is this defined during training of the model?

2023-10-12 00:21 UTC, mauch approved these changes
Looks good to me.

We could add the newly minted annotation class names from the COCO JSON from [here](https://github.com/Sydney-Informatics-Hub/aerial-segmentation/blob/d26b005fc89565aeb6dd8a8ccc9f2861836953d7/aerialseg/utils.py#L233) at some point as well. The JSON could also give you `NUM_CLASSES` if you want it.

2023-10-12 06:25 UTC, sahandv approved these changes
Looks good to me as a PoC.

2023-10-12 06:25 UTC, sahandv commented on scripts/poc_gradio.py
> +cfg.MODEL.ROI_HEADS.NUM_CLASSES = 8
In my opinion, given that we already know which model is being used, we can hard-code it. But in the next release, if we make the model selectable, we should also make sure this is properly selected as well. The same goes for the threshold.

2023-10-12 06:29 UTC, merged