Benchmarking Scripts
Sydney-Informatics-Hub/aerial-segmentation pull request #26
Opened 2023-09-28 05:48 UTC by hlydecker

2023-09-29 00:29 UTC, mauch requested changes
Mostly looks fine to me. Just a bunch of minor comments.

I have one slightly broader issue to do with how this repository is set up. In this PR you are putting everything into a package called `aerial-seg` including scripts and modules. In my recent PR (#27) I've put the standalone scripts in a `scripts` directory under root of the repo. We should discuss the structure of the repo and e.g. where we want scripts vs. modules to go before things become too messy :)

My `/scripts` method is the way I have done it in the past since I've always used `setuptools` and point a `setup.py` file to the scripts dir for pip installs.

I'm also happy to put scripts straight into the package dir - I just think we both need to do it  the same way :)

2023-09-29 00:29 UTC, mauch commented on aerial-seg/__init__.py
I'm not sure Python plays nice when you use module names with hyphens (Not to mention that the PEP8 brigade will be most displeased). Perhaps `areial_seg` rather than `aerial-seg`?

2023-09-29 04:24 UTC, hlydecker commented on aerial-seg/benchmark.py
> +from detectron2.utils.visualizer import Visualizer, ColorMode
Will do! I wrote and committed these directly into the github add file UI ;)

2023-09-29 04:25 UTC, hlydecker commented on aerial-seg/benchmark.py
> +    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 8
The only reason why I specified these here was because I ran into issues with the config not properly loading things; I'll test and then remove if possible.

2023-09-29 04:25 UTC, hlydecker commented on aerial-seg/benchmark.py
> +        if filename.endswith(".jpg") or filename.endswith(".png"):
No reason not to! I'll add it.

2023-09-29 04:26 UTC, hlydecker commented on aerial-seg/__init__.py
good catch

2023-09-29 04:46 UTC, xinwei89 commented on aerial-seg/utils.py
> +    """
Can I ask why we would want to save images together as a gif? Is it easier to visualise the the annotated results or any other reason?

2023-09-29 04:46 UTC, xinwei89 commented on scripts/benchmark.py
> +    print(f"Average Iteration Time: {avg_iteration_time:.2f} s")
Is the current benchmarking script only interested in the time it takes to make a prediction? Should we be adding other aspects to benchmark later on?

2023-10-02 22:49 UTC, mauch approved these changes

2023-10-04 08:07 UTC, hlydecker commented on scripts/benchmark.py
> +    print(f"Average Iteration Time: {avg_iteration_time:.2f} s")
Yes good idea! next version :)

2023-10-04 08:08 UTC, merged