Shape regularisation and bug fixes
Sydney-Informatics-Hub/aerial-segmentation pull request #34
Opened 2023-10-11 03:11 UTC by sahandv

In this version, the following changed:

- Added default 0.9 to shape simplification tolerance 
- Added minimum rotated rectangle (MRR) option to use instead of simplification. If this is set, simplification will be ignored.
- Fixed a bug with the saved images.

In case MRR is set, the rectangles in the corners will not look very good. However, this will make sure the shapes are as compact and simple as possible. This **partially** addresses [aerial-conversion issue #19](https://github.com/Sydney-Informatics-Hub/aerial-conversion/issues/19).

The following is a good-looking sample for the minimum rotated rectangles:
![Screenshot from 2023-10-11 14-00-22](https://github.com/Sydney-Informatics-Hub/aerial-segmentation/assets/10245721/bdeb4709-84ef-4f9c-a805-402542eba5b2)

And the next one is a not-very good-looking one:
![Screenshot from 2023-10-11 14-03-34](https://github.com/Sydney-Informatics-Hub/aerial-segmentation/assets/10245721/ee44262e-daa6-489f-b008-265772d16f95)

Note: predictions are not good, but this version has nothing to do with them.

2023-10-11 04:30 UTC, xinwei89 commented on scripts/prediction_batch_detectron2.py
> +            )
Is this supposed to be `out = os.path.join(
                args.indir, f"coco-out-tol_{str(args.simplify_tolerance)}.json"
            )`

2023-10-11 04:37 UTC, xinwei89 commented on scripts/prediction_batch_detectron2.py
Was just thinking, to avoid future confusion, maybe we should add a function for coco objects to save the coco json to a file.

2023-10-12 00:09 UTC, sahandv commented on scripts/prediction_batch_detectron2.py
Thanks for the PR. Done.

2023-10-12 00:18 UTC, sahandv commented on scripts/prediction_batch_detectron2.py
> +            )
yup. Good catch! Forgot to fix it while debugging the outputs. 
Also used the new function here in the new version.

2023-10-12 00:21 UTC, xinwei89 commented on scripts/prediction_batch_detectron2.py
> +    f.write(coco_json.write_to_file(out))
`coco_json.write_to_file(out)` should write the json to file, I don't think `f.write` is needed

2023-10-12 00:26 UTC, xinwei89 requested changes

2023-10-12 00:26 UTC, xinwei89 commented on scripts/prediction_batch_detectron2.py
> +    f.write(coco_json.write_to_file(out))
Actually I think we also need to define `out` for the case when `args.coco_out` is not None

2023-10-12 00:26 UTC, xinwei89 commented on scripts/prediction_batch_detectron2.py
> +    f.write(coco_json.write_to_file(out))
`coco_json.write_to_file(out)` should write the json to file, I don't think `f.write` is needed

2023-10-12 00:33 UTC, sahandv commented on scripts/prediction_batch_detectron2.py
> +    f.write(coco_json.write_to_file(out))
Thanks! I rushed to fix it and missed it. Fixed

2023-10-12 00:33 UTC, sahandv commented on scripts/prediction_batch_detectron2.py
> +    f.write(coco_json.write_to_file(out))
Fixed

2023-10-12 00:36 UTC, sahandv commented on scripts/prediction_batch_detectron2.py
> +    f.write(coco_json.write_to_file(out))
I actually don't need the case, I just had to change the code back to `coco_json.write_to_file(args.coco_out)`

2023-10-12 00:37 UTC, xinwei89 approved these changes
This looks good to me!

2023-10-12 00:37 UTC, merged